export const ingredientsInfo = [
    {
        name: 'cutlet',
        image: cutlet,
        price: 7.80,
        gram: 350,
        kcal: 280,
    },
    {
        name: 'mayo',
        image: mayo,
        price: 2.00,
        gram: 30,
        kcal: 40,
    },
    {
        name: 'onion',
        image: onion,
        price: 1.50,
        gram: 12,
        kcal: 4,
    },
    {
        name: 'tomato',
        image: tomato,
        price: 4.20,
        gram: 48,
        kcal: 4,
    },
    {
        name: 'cucumber',
        image: cucumber,
        price: 3.50,
        gram: 7,
        kcal: 2,
    },
    {
        name: 'cheese',
        image: cheese,
        price: 5.10,
        gram: 40,
        kcal: 40,
    },
    {
        name: 'salad',
        image: salad,
        price: 3.20,
        gram: 6,
        kcal: 3,
    },
    {
        name: 'bun',
        image: bun,
        price: 1.00,
        gram: 10,
        kcal: 120,
    },
    {
        name: 'bunTop',
        image: bunTop,
        price: 1.00,
        gram: 10,
        kcal: 120,
    },
];
